WIP: Add snippets collection
prettier-snippets/vscode-prettier-snippets-react pull request #15
Opened 2017-11-19 13:25 UTC by prichodko

2017-11-19 14:37 UTC, prichodko commented
There are a few other React-related imports I use all the time:
- React Router
- Redux (separate extensions probably)
- styled-components

2017-11-19 15:22 UTC, prichodko commented
/await #17

2017-11-21 12:06 UTC, felicio requested changes
Good job. Just a couple of cosmetic points from my side really.

2017-11-21 12:06 UTC, felicio commented on snippets/snippets.json
> +  "rccs": {
I get that naming snippet object "React Stateful Class Component" can be somewhat cumbersome, but would you agree that is more descriptive and, strangely enough, easier on the eye?

2017-11-21 12:06 UTC, felicio commented on snippets/snippets.json
> +
Could we left out these blank lines from the JSON, or are they here for better visualization purposes?

2017-11-21 12:06 UTC, felicio commented on snippets/snippets.json
> +    "description": "Import React."
Shouldn't we omit the full stop (.)? Since `description` does not happen to be a sentence, really.

2017-11-21 12:06 UTC, felicio commented on snippets/snippets.json
> +    "body": "import React from 'react'\n$1",
I'm not a fan of enforcing new lines insertion on the user. Plus snippets get final tab stop added to its end by default, so there's no need for `$1`.

2017-11-21 12:06 UTC, felicio commented on snippets/snippets.json
> +      "state = $2",
`"\tstate = {$2}\n"`, maybe?

2017-11-21 21:24 UTC, felicio approved these changes

2017-11-21 21:25 UTC, merged